dist: trusty
sudo: false
language: cpp
compiler: clang
install:
  - curl -sSf https://sh.rustup.rs | sh -s -- -y --verbose --default-toolchain nightly
  - ~/.cargo/bin/rustup target add x86_64-unknown-linux-musl
cache:
  directories:
    - ~/.cargo
    - ~/.rustup
script: ~/.cargo/bin/cargo build --target x86_64-unknown-linux-musl --verbose --release
deploy:
  provider: releases
  api_key:
    secure: SIVx4lutxHcVgj/LXdJbDZhAQdIrOoY8LdDK75Bw1FHnWIWJCp5eBtJ8N2zh4wz1gSFHkJtnOaP9i46vYRhvVldjnjrYbKMfk5cN+65jgoy0VxoVsXRgIbqDP1aWjbNv0P7vHfsXONQrldsPk1p5QUCtCNCpYkx3ikSLu4dxDiwMKJkmW6AiRa4SAsr8QDzKQwwlWokL2M0Z97AokSu4XJfJ8WtF5vu5Y6m2xjROn2+Kem1Leu8y67YBMin4YJrLzJ0nDeHJKJg2NK3mUMjhSMcFjflWUXNnv7UdLUxYCoiCEksRgeX1syrEgx9Xok1sVqdmwjmXpxGKPH/dbgHCFCd2S/6YEjYCBmuPxB2AJfz0YuJ/X5Xko1hz3Hs4rkpmhqwHzf4nmk+t4Yv72wAlL8FRHQcAb5lSXwapOZZLWoLbHipOl0um6cJ2EoMRtZmMQyz8ErIUzJcBWVYXJw0JQysGMxMDna8s63tGHl5Uj3npxFci5lCDCYh00aF9YAiVO8O3JrE961WmTos2i0Nb8V/+aP0bwBqUEs1XQzw33OdhDe3gTBMzmkbIVIpaR3ztgC9SLJLszrTF+GaIg+HosnRg75YYpUNHQGx6HKcr+O6tQ3y6GWxmFaAFzfS3DRtOJ5xj+ivY5pzbOBAxt+M6mnL/yhfX7s1T6gwCi7TbDt4=
  file: target/x86_64-unknown-linux-musl/release/wdscli
  skip_cleanup: true
  on:
    tags: true
