dist: trusty
sudo: false
language: cpp
os:
  - linux
  - osx

install:
  - curl -sSf https://sh.rustup.rs | sh -s -- -y --verbose --default-toolchain nightly
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ~/.cargo/bin/rustup target add x86_64-unknown-linux-musl ; fi

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
    - $TRAVIS_BUILD_DIR/target

script: ./travis-script.sh

before_deploy:
  - mv target/x86_64-unknown-linux-musl/release/wdscli wdscli.linux || true
  - mv target/release/wdscli wdscli.macos || true
  - ls -l wdscli.*

deploy:
  provider: releases
  api_key:
    secure: bIRysY4UcXbyGfFPW80ZVA1hw92xt19sQnD6UGPIWdyEVVsRJ5ctgOLz8ZesVrxpr/TT0x6/UrW+OHgHBF1CWNaHmQ40UMuXOMqzOy9oDWRyPc2lO0qZkBT/0qqDO1QqKmmouPlD61kqvVWmrDlHMgVo22ifv3W049FpSUzJW3rcZvh25ObpaVK08yJumS2p5V8dOjwAzb6yzcLcgCWEXX5z3OOzpUbQRe3HexkLo0tGKbLjQoQ9gXoIvsB6ZGXCHmtIlX0QYdmdjA25LyKR2fraPU17i/DVm9nX359XvVQNuMihl4AT8pbKVhyEqCLk3IP8CStQ/ug5EDOjehIMNVg+X9qdJtwNDiEZN5N2cAQxTF3USw62d8V8oBGlPaTnG4YAe8Hh+8zN5ebngLtDqkO+rMbccQMWydITphnoizExy2EQ5NDpIzxTUCKnx4OphTqoJWM7J+BeFRSVsyH2gQWtGayaRE3XjV6e0UUDqg2SIZAAiYVRqJ18cCrcRJnRgyeXMsVrQyoa17WAFsz40PmHy6/XAEeKQpmTn01pbxPk3PvDoRPMh61t3iJcNVBFMzDmJftvUgtzV7z6nq4lEtb7YfOvJ788aJs4IBHuNKwr0cQzr6Qhv+OgWl3w8joYGu1VJch265U3bXtTX97eFp8zedjU51SnufVLRNlV+Hs=
  file_glob: true
  file: wdscli.*
  skip_cleanup: true
  on:
    repo: bruceadams/wdscli
    tags: true

after_deploy: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl --data build=true https://registry.hub.docker.com/u/bruceadams/wdscli/trigger/3a6677b7-9b9b-4961-b3f1-f27c9e114b60/ ; fi
