install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

cache:
  - C:\Users\appveyor\.cargo
  - target

build_script: cargo build --release

before_deploy: mv target\release\wdscli wdscli.windows

deploy:
  artifact: wdscli.windows
  auth_token:
    secure: 7rRYeQDL+tzJ/spq181++1gXdlugmdfw/itAl3sMq6MQrPhDDSgSefGkpGSJvJgE
  description: ''
  on:
    RUST_VERSION: nightly
    appveyor_repo_tag: true
  provider: GitHub
