install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

cache:
  - C:\Users\appveyor\.cargo
  - C:\Users\appveyor\.rustup
  - target

build_script: cargo build --release

artifacts:
  - path: target\release\wdscli.exe
    name: wdscli

deploy:
  artifact: wdscli
  auth_token:
    secure: 7rRYeQDL+tzJ/spq181++1gXdlugmdfw/itAl3sMq6MQrPhDDSgSefGkpGSJvJgE
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub
