[package]
name = "wdscli"
version = "1.1.1"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
description = "Basic administration for Watson Discovery Service."

[dependencies.wdsapi]
git = "https://github.com/bruceadams/wdsapi.git"

[dependencies]
chrono = "0.2"
clap = "2.20.0"
serde_json = "0.8"
rayon = "0.6"
