[package]
name = "wdscli"
version = "0.5.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]

[dependencies.wdsapi]
git = "https://github.com/bruceadams/wdsapi.git"

[dependencies]
clap = "2.20.0"
serde_json = "0.8"
rayon = "0.6"
