[package]
name = "wdscli"
version = "2.0.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
description = "Basic administration for Watson Discovery Service."

[dependencies.wdsapi]
git = "https://github.com/bruceadams/wdsapi.git"
branch  "version-2"

[dependencies]
chrono = "0"
clap = "2"
serde_json = "0"
rayon = "0"
