[package]
name = "wdscli"
version = "2.1.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]
description = "Basic administration for Watson Discovery Service."

[dependencies.wdsapi]
git = "https://github.com/bruceadams/wdsapi.git"

[dependencies]
chrono = "0"
clap = "2"
crossbeam = "0"
hyper = "0"
serde_json = "0"
rayon = "0"
walkdir = "1"
